model_name: DADHEAD

seed: 42

split_dir: ./data/splits

# target_size: !<tag:yaml.org,2002:seq> [256,256] do I need this?

device: cpu

num_epochs: 100

leaky_relu_slope: 0.01
loss_weight_t: 0.01
lr: 0.0001
batch_size: 64
iterations: 200000
beta_1: 0.9
beta_2: 0.999

