
model_name: LOCALNET

seed: 42

split_dir: ./data/splits

# image size should be 33 x 33 x 3 for Local-Net
target_size: !<tag:yaml.org,2002:seq> [33,33]

device: cpu

num_epochs: 100

# k balances distillations loss
# c balances compactness loss
loss_weight_k: 1.0
loss_weight_c: 1.0
lr: 0.0002
beta_1: 0.9
beta_2: 0.999
leaky_relu_slope: 0.005

batch_size: 16
iterations: 50000



