model_name: LOCALNET_FT

seed: 42

local_net_output_dimensions: 128
resnet_output_dimensions: 512

# k balances distillations loss
# c balances compactness loss
loss_weight_k: 1.0
loss_weight_c: 1.0
lr: 0.0002
beta_1: 0.9
beta_2: 0.999
leaky_relu_slope: 0.005

batch_size: 16
iterations: 50000



